### ISSUE TITLE
Token indices sequence length is longer

### ISSUE THREAD

**Issue by ziat007** [Aemon-Algiz/DatesetExtraction#4]
I am getting this error, I wish this project got some updates, it is exactly what I need.
Token indices sequence length is longer than the specified maximum sequence length for this model (283994 > 4096). Running this sequence through the model will result in indexing errors
Traceback (most recent call last):
  File "D:\GPT\DatesetExtraction-main\BookParse.py", line 115, in <module>
    response = submit_to_api(tokenizer.decode(chunk))
  File "D:\GPT\DatesetExtraction-main\BookParse.py", line 101, in submit_to_api
    print(f"Request failed: {e}")
UnboundLocalError: local variable 'e' referenced before assignment

**Comment by 7071eth** [comment]
I am having the same issue. Is your issue resolved?

**Comment by 7071eth** [comment]
My issue is resolved. Thie reason why it happened is because the api wasnt enabled. Hope it solves your issue too

**Comment by ziat007** [comment]
> My issue is resolved. Thie reason why it happened is because the api wasnt enabled. Hope it solves your issue too

I have the API enabled and working in other applications.
How have you got this setup? I have tried changing the values to what works on other apps to no sucess.
HOST = 'localhost:5000'
URI = 'http://{HOST}/api/v1/chat'

working app: http://127.0.0.1:5000/api
and this: ws://127.0.0.1:5005/api/v1/stream
